# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AR1 <- function(series, p = 1L) {
    .Call(`_RcppBVAR_AR1`, series, p)
}

conj_delta <- function(series, delt, AR1type = FALSE) {
    .Call(`_RcppBVAR_conj_delta`, series, delt, AR1type)
}

prepData <- function(series, p, include_const = TRUE) {
    .Call(`_RcppBVAR_prepData`, series, p, include_const)
}

ARp <- function(series, p = 1L) {
    .Call(`_RcppBVAR_ARp`, series, p)
}

conj_delta <- function(series, delt, deltAR1type = FALSE) {
    .Call(`_RcppBVAR_conj_delta`, series, delt, deltAR1type)
}

conj_sigma <- function(series, sig2_lag, carriero_hack = FALSE) {
    .Call(`_RcppBVAR_conj_sigma`, series, sig2_lag, carriero_hack)
}

conj_lam2dum <- function(series, lam, p, delt, s2_lag = 1L, Z = NULL, y_bar_type = "initial", include_const = TRUE, delttypeAR1 = FALSE, carriero_hack = FALSE) {
    .Call(`_RcppBVAR_conj_lam2dum`, series, lam, p, delt, s2_lag, Z, y_bar_type, include_const, delttypeAR1, carriero_hack)
}

conj_dum2hyp <- function(Y_star, X_star) {
    .Call(`_RcppBVAR_conj_dum2hyp`, Y_star, X_star)
}

conj_simulate <- function(v_post, Omega_root_post, S_post, Phi_post, verbose = FALSE, keep = 10L, chains = 1L) {
    .Call(`_RcppBVAR_conj_simulate`, v_post, Omega_root_post, S_post, Phi_post, verbose, keep, chains)
}

BVAR_cniw_setup <- function(series, lam, p, delt, v_prior, s2_lag = 1L, Z = NULL, y_bar_type = "initial", include_const = TRUE, delttypeAR1 = FALSE, carriero_hack = FALSE) {
    .Call(`_RcppBVAR_BVAR_cniw_setup`, series, lam, p, delt, v_prior, s2_lag, Z, y_bar_type, include_const, delttypeAR1, carriero_hack)
}

BVAR_cniw_est <- function(setup, keep, verbose = FALSE, n_chains = 1L) {
    .Call(`_RcppBVAR_BVAR_cniw_est`, setup, keep, verbose, n_chains)
}

BVAR <- function(series, p, C, V0, Phi0, df = 5L, include_mean = TRUE) {
    .Call(`_RcppBVAR_BVAR`, series, p, C, V0, Phi0, df, include_mean)
}

Forecast <- function(model, h) {
    .Call(`_RcppBVAR_Forecast`, model, h)
}

freqVAR <- function(series, p, include_mean = TRUE) {
    .Call(`_RcppBVAR_freqVAR`, series, p, include_mean)
}

rcpparma_hello_world <- function() {
    .Call(`_RcppBVAR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_RcppBVAR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_RcppBVAR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_RcppBVAR_rcpparma_bothproducts`, x)
}

