# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Forecast <- function(model, h) {
    .Call(`_RcppBVAR_Forecast`, model, h)
}

freqVAR <- function(series, p) {
    .Call(`_RcppBVAR_freqVAR`, series, p)
}

rcpparma_hello_world <- function() {
    .Call(`_RcppBVAR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_RcppBVAR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_RcppBVAR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_RcppBVAR_rcpparma_bothproducts`, x)
}

